### ISSUE TITLE
Push plugin fails on Android 6

### ISSUE THREAD

**Issue by dtopuzov** [NativeScript/push-plugin#2]
Steps to reproduce: 
Run [sample-push-plugin](https://github.com/NativeScript/sample-push-plugin) app.
Tap "Enable Notifications"

Result: 
```
10-28 12:25:02.763  2309  2309 W AccessibilityNodeInfoDumper: Fetch time: 0ms
10-28 12:25:02.773  2394  2394 W System  : ClassLoader referenced unknown path: /system/priv-app/Settings/lib/x86
10-28 12:25:02.793  1877  2408 E GCM     : Missing checkin config file
10-28 12:25:02.793  1877  2408 W GCM     : GCM FAILED TO INITIALIZE - missing checkin
10-28 12:25:02.923  1290  1475 I ActivityManager: Start proc 2411:com.android.calendar/u0a20 for broadcast com.android.calendar/.widget.CalendarAppWidgetService$CalendarFactory
10-28 12:25:02.930  2411  2411 I art     : Late-enabling JIT
10-28 12:25:02.932  2411  2411 I art     : JIT created with code_cache_capacity=2MB compile_threshold=1000
10-28 12:25:02.939  2338  2338 V JS      : EverliveError: Error while retrieving a token: AUTHENTICATION_FAILED
10-28 12:25:02.940  2338  2383 W System.err: java.io.IOException: AUTHENTICATION_FAILED
10-28 12:25:02.940  2338  2383 W System.err: 	at com.google.android.gms.iid.zzc.zzb(Unknown Source)
10-28 12:25:02.940  2338  2383 W System.err: 	at com.google.android.gms.iid.zzc.zza(Unknown Source)
10-28 12:25:02.940  2338  2383 W System.err: 	at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
10-28 12:25:02.940  2338  2383 W System.err: 	at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
10-28 12:25:02.940  2338  2383 W System.err: 	at com.telerik.pushplugin.ObtainTokenThread.getTokenFromGCM(ObtainTokenThread.java:40)
10-28 12:25:02.940  2338  2383 W System.err: 	at com.telerik.pushplugin.ObtainTokenThread.run(ObtainTokenThread.java:31)
```

**Comment by AntonDobrev** [comment]
@dtopuzov Could you please check that you have Google Play Services installed on this device and they are enabled?

**Comment by AntonDobrev** [comment]
This is not reproducible with the latest release https://github.com/NativeScript/push-plugin/commit/40027ed72d50f167614e8f3fc3933df8de194c78 too.
