### ISSUE TITLE
_this.updateMessage is not a function

### ISSUE THREAD

**Issue by lumayara** [NativeScript/push-plugin#235]
I sent a message from Firebase and right away my emulator took me to an error: 
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method success failed

TypeError: _this.updateMessage is not a function
File: "file:///data/data/org.nativescript.LCGIncConnect/files/app/main.js, line: 17, column: 14

StackTrace: 
	Frame: function:'notificationCallbackAndroid', file:'file:///data/data/org.nativescript.LCGIncConnect/files/app/main.js', line: 17, column: 15


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.access$2300(Runtime.java:34)
	at com.tns.Runtime$3.run(Runtime.java:1112)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
### Which platform(s) does your issue occur on?
- Android
- emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.1.1
- Cross-platform modules: 3.4.1
- Runtime(s): tns-ios: 4.1.1, tns-android: 4.1.3
- Plugin(s): 
```
"dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "email-validator": "^1.1.1",
    "nativescript-angular": "~5.2.0",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-modal-datetimepicker": "^1.1.3",
    "nativescript-oauth": "^2.1.2",
    "nativescript-platform-css": "^1.6.5",
    "nativescript-push-notifications": "^1.1.4",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-dataform": "^3.5.0",
    "nativescript-ui-listview": "^3.5.2",
    "nodeify": "^1.0.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.0",
    "tns-core-modules": "^3.4.1",
    "zone.js": "~0.8.4"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "css-font-family": "^1.0.7",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.6.0",
    "typescript": "~2.6.2"
  }
```

In my main.ts I have:
```
import * as pushPlugin from "nativescript-push-notifications";
//other code
var pushSettings = {
    senderID: "4394239484298 //Im just putting a random ID, it is not the one I am using", 
    notificationCallbackAndroid: (stringifiedData: String, fcmNotification: any) => {
        const notificationBody = fcmNotification && fcmNotification.getBody();
        this.updateMessage("New message!\n" + notificationBody + "\n" + stringifiedData);
    }
};
pushPlugin.register(pushSettings, (token: String) => {
    alert("Device registered. Access token: " + token);;
}, function() { });

//other code
```

Is there anything I am doind wrong?

**Comment by fthuin** [comment]
Yes, you did not define updateMessage() inside your class, the code inside the notificationCallback is just an example taken from the demo of this repo. You have to write your own callback logic with your own methods. Take a look at the demo code if you want to reuse the `updatedMessage` function.

**Comment by lini** [comment]
You can also try replacing `this.updateMessage(` with `alert(` or `console.log(` in your code if you just want to see the notification body.

**Comment by lumayara** [comment]
Thank you, @fthuin and @lini ! Now it works :)
