### ISSUE TITLE
Plugin not compatible with nativescript v2.0

### ISSUE THREAD

**Issue by rossaffandy** [NativeScript/push-plugin#25]
Plugin is not compatible with nativescript v2.0

**Comment by mnesarco** [comment]
After upgraded to 2.0 i have this exception. Is there any workaround?

```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Fail to load module: /data/data/**********/files/app/app.js

Error: java.lang.RuntimeException: The application is null, it's not passed correctly!
    com.telerik.pushplugin.PushLifecycleCallbacks.registerCallbacks(PushLifecycleCallbacks.java:26)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:241)
    com.tns.Runtime.run(Runtime.java:235)
    com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:129)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:13)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4657)
    android.app.ActivityThread.access$1500(ActivityThread.java:155)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5376)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'', file:'/data/data/**********/files/app/tns_modules/nativescript-push-notifications/push-plugin.js', line: 8, column: 55
Frame: function:'', file:'/data/data/**********/files/app/tns_modules/nativescript-push-notifications/push-plugin.js', line: 9, column: 7
Frame: function:'', file:'/data/data/**********/files/app/tns_modules/nativescript-push-notifications/push-plugin.js', line: 51, column: 3
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/**********/files/app/shared/application.js', line: 10, column: 18
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/**********/files/app/app.js', line: 4, column: 17
Frame: function:'require', file:'', line: 1, column: 266

at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4660)
at android.app.ActivityThread.access$1500(ActivityThread.java:155)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5376)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: com.tns.NativeScriptException: 
Fail to load module: /data/data/**********/files/app/app.js

Error: java.lang.RuntimeException: The application is null, it's not passed correctly!
    com.telerik.pushplugin.PushLifecycleCallbacks.registerCallbacks(PushLifecycleCallbacks.java:26)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:241)
    com.tns.Runtime.run(Runtime.java:235)
    com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:129)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:13)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4657)
    android.app.ActivityThread.access$1500(ActivityThread.java:155)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5376)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
File: "<unknown>, line: 1, column: 265

StackTrace: 
Frame: function:'', file:'/data/data/**********/files/app/tns_modules/nativescript-push-notifications/push-plugin.js', line: 8, column: 55
Frame: function:'', file:'/data/data/**********/files/app/tns_modules/nativescript-push-notifications/push-plugin.js', line: 9, column: 7
Frame: function:'', file:'/data/data/**********/files/app/tns_modules/nativescript-push-notifications/push-plugin.js', line: 51, column: 3
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/**********/files/app/shared/application.js', line: 10, column: 18
Frame: function:'require', file:'', line: 1, column: 266
Frame: function:'', file:'/data/data/**********/files/app/app.js', line: 4, column: 17
Frame: function:'require', file:'', line: 1, column: 266

at com.tns.Runtime.runModule(Native Method)
at com.tns.Runtime.runModule(Runtime.java:241)
at com.tns.Runtime.run(Runtime.java:235)
at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:129)
at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:13)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4657)
... 9 more
Caused by: java.lang.RuntimeException: The application is null, it's not passed correctly!
at com.telerik.pushplugin.PushLifecycleCallbacks.registerCallbacks(PushLifecycleCallbacks.java:26)
... 16 more

```

**Comment by mnesarco** [comment]
This workaround suggested by @triniwiz works well.

```
var application = require("application");
    application.start({ moduleName: "main-page" });
    application.on(application.launchEvent, function (args) {
        if (args.android) {
            var gcm = require("nativescript-push-notifications");
            gcm.register({ senderID: 'projectid' }, function (data) {
                self.set("message", "" + JSON.stringify(data));
            }, function () { });
            if (gcm.onMessageReceived) {
                gcm.onMessageReceived(function callback(data) {
                    console.log("message received:::: ", "" + JSON.stringify(data));
    
                });
            }
    
        } else if (args.ios !== undefined) {
            //Do ios stuff here
        }
    });
```

**Comment by AntonDobrev** [comment]
@rossaffandy @mnesarco 

Please see my comments in #20 

The approach suggested by @mnesarco should be valid as well.
