### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by ickata** [NativeScript/push-plugin#33]
Hi,

Android build fails on my side:

```
:compileF0F1F2F3DebugNdk UP-TO-DATE
:compileF0F1F2F3DebugSources
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class com.google.android.gms.iid.zzb$zza$zza conflict: /Users/ickata/Desktop/Tables/tns/sample-Groceries/platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-gcm/8.4.0/jars/classes.jar and /Users/ickata/Desktop/Tables/tns/sample-Groceries/platforms/android/build/intermediates/exploded-aar/com.google.android.gms/play-services-basement/9.2.0/jars/classes.jar
	at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:39)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

I have the following plugins:

```
┌─────────────────────────────────┬─────────┐
│ Plugin                          │ Version │
│ nativescript-geolocation        │ 0.0.12  │
│ nativescript-google-maps-sdk    │ ^1.3.2  │
│ nativescript-push-notifications │ 0.0.15  │
│ tns-core-modules                │ 2.1.0   │
└─────────────────────────────────┴─────────┘
```

Without the push plugin build is successful.

Please advise.

**Comment by AntonDobrev** [comment]
@ickata 

Thanks for your report. Please see my reply to #29 . The issue here appears to be a conflict between Google Play Services SDK 8.4 (used by this plugin) and another plugin (Google Maps) using the latest one. 

For now you may need to configure manually the push module.

**Comment by ickata** [comment]
Thanks. Changing this line:

```compile 'com.google.android.gms:play-services-gcm:8.4.0'```

to:

```compile 'com.google.android.gms:play-services-gcm:+'```

in ```./node_modules/nativescript-push-notifications/platforms/android/include.gradle``` solved the build issue.

**Comment by ickata** [comment]
However, the app cannot start on android. Here's the log:

```
java.lang.RuntimeException: Unable to resume activity {org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
    maps.z.k.a(Unknown Source)
    maps.x.c.a(Unknown Source)
    com.google.android.gms.maps.internal.CreatorImpl.b(Unknown Source)
    com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(Unknown Source)
    vi.onTransact(:com.google.android.gms.DynamiteModulesB:79)
    android.os.Binder.transact(Binder.java:361)
    pex.newMapViewDelegate(:com.google.android.gms:204)
    com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms:111)
    pew.onTransact(:com.google.android.gms:79)
    android.os.Binder.transact(Binder.java:361)
    com.google.android.gms.maps.internal.zzc$zza$zza.zza(Unknown Source)
    com.google.android.gms.maps.MapView$zzb.zzbpt(Unknown Source)
    com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
    com.google.android.gms.dynamic.zza.zza(Unknown Source)
    com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
    com.google.android.gms.maps.MapView.onCreate(Unknown Source)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
    com.tns.Runtime.callJSMethod(Runtime.java:712)
    com.tns.Runtime.callJSMethod(Runtime.java:693)
    com.tns.Runtime.callJSMethod(Runtime.java:683)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:35)
    android.app.Fragment.performCreateView(Fragment.java:1700)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
    android.app.BackStackRecord.run(BackStackRecord.java:684)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
    android.app.Activity.performResume(Activity.java:5321)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2764)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
    android.app.ActivityThread.access$800(ActivityThread.java:135)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:136)
    android.app.ActivityThread.main(ActivityThread.java:5001)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    dalvik.system.NativeStart.main(Native Method)
File: "/data/data/org.nativescript.demo/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js, line: 161, column: 22

StackTrace: 
Frame: function:'MapView._createUI', file:'/data/data/org.nativescript.demo/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js', line: 161, column: 23
Frame: function:'View._onContextChanged', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 191, column: 14
Frame: function:'View._onAttached', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 143, column: 14
Frame: function:'eachChild', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 148, column: 23
Frame: function:'LayoutBase._eachChildView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 146, column: 22
Frame: function:'View._onAttached', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 154, column: 18
Frame: function:'eachChild', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 148, column: 23
Frame: function:'ContentView._eachChildView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/page/page-common.js', line: 265, column: 41
Frame: function:'View._onAttached', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 154, column: 18
Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 119, column: 18
Frame: function:'View._addView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view-common.js', line: 921, column: 14
Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
Frame: function:'FragmentClass.onCreateView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38

at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2774)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
at android.app.ActivityThread.access$800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
    maps.z.k.a(Unknown Source)
    maps.x.c.a(Unknown Source)
    com.google.android.gms.maps.internal.CreatorImpl.b(Unknown Source)
    com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(Unknown Source)
    vi.onTransact(:com.google.android.gms.DynamiteModulesB:79)
    android.os.Binder.transact(Binder.java:361)
    pex.newMapViewDelegate(:com.google.android.gms:204)
    com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms:111)
    pew.onTransact(:com.google.android.gms:79)
    android.os.Binder.transact(Binder.java:361)
    com.google.android.gms.maps.internal.zzc$zza$zza.zza(Unknown Source)
    com.google.android.gms.maps.MapView$zzb.zzbpt(Unknown Source)
    com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
    com.google.android.gms.dynamic.zza.zza(Unknown Source)
    com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
    com.google.android.gms.maps.MapView.onCreate(Unknown Source)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
    com.tns.Runtime.callJSMethod(Runtime.java:712)
    com.tns.Runtime.callJSMethod(Runtime.java:693)
    com.tns.Runtime.callJSMethod(Runtime.java:683)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:35)
    android.app.Fragment.performCreateView(Fragment.java:1700)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
    android.app.BackStackRecord.run(BackStackRecord.java:684)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
    android.app.Activity.performResume(Activity.java:5321)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2764)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2803)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
    android.app.ActivityThread.access$800(ActivityThread.java:135)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:136)
    android.app.ActivityThread.main(ActivityThread.java:5001)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    dalvik.system.NativeStart.main(Native Method)
File: "/data/data/org.nativescript.demo/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js, line: 161, column: 22

StackTrace: 
Frame: function:'MapView._createUI', file:'/data/data/org.nativescript.demo/files/app/tns_modules/nativescript-google-maps-sdk/map-view.js', line: 161, column: 23
Frame: function:'View._onContextChanged', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 191, column: 14
Frame: function:'View._onAttached', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 143, column: 14
Frame: function:'eachChild', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 148, column: 23
Frame: function:'LayoutBase._eachChildView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 146, column: 22
Frame: function:'View._onAttached', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 154, column: 18
Frame: function:'eachChild', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 148, column: 23
Frame: function:'ContentView._eachChildView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/page/page-common.js', line: 265, column: 41
Frame: function:'View._onAttached', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 154, column: 18
Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view.js', line: 119, column: 18
Frame: function:'View._addView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/core/view-common.js', line: 921, column: 14
Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
Frame: function:'FragmentClass.onCreateView', file:'/data/data/org.nativescript.demo/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
at com.tns.Runtime.callJSMethod(Runtime.java:712)
at com.tns.Runtime.callJSMethod(Runtime.java:693)
at com.tns.Runtime.callJSMethod(Runtime.java:683)
at com.tns.FragmentClass.onCreateView(FragmentClass.java:35)
at android.app.Fragment.performCreateView(Fragment.java:1700)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
at android.app.BackStackRecord.run(BackStackRecord.java:684)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
at android.app.Activity.performResume(Activity.java:5321)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2764)
... 12 more
Caused by: java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
at maps.z.k.a(Unknown Source)
at maps.x.c.a(Unknown Source)
at com.google.android.gms.maps.internal.CreatorImpl.b(Unknown Source)
at com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(Unknown Source)
at vi.onTransact(:com.google.android.gms.DynamiteModulesB:79)
at android.os.Binder.transact(Binder.java:361)
at pex.newMapViewDelegate(:com.google.android.gms:204)
at com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms:111)
at pew.onTransact(:com.google.android.gms:79)
at android.os.Binder.transact(Binder.java:361)
at com.google.android.gms.maps.internal.zzc$zza$zza.zza(Unknown Source)
at com.google.android.gms.maps.MapView$zzb.zzbpt(Unknown Source)
at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
at com.google.android.gms.dynamic.zza.zza(Unknown Source)
at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
```

**Comment by ickata** [comment]
Also adding the extracted AndroidManifest.xml:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="org.nativescript.sampleGroceries" platformBuildVersionCode="23" platformBuildVersionName="6.0-2704002">
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
    <supports-screens android:largeScreens="true" android:normalScreens="true" android:smallScreens="true" android:xlargeScreens="true"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-feature android:glEsVersion="0x20000" android:required="true"/>
    <application android:allowBackup="true" android:debuggable="true" android:icon="@drawable/icon" android:label="@string/app_name" android:name="com.tns.NativeScriptApplication" android:supportsRtl="true" android:theme="@style/AppTheme">
        <meta-data android:name="com.google.android.geo.API_KEY" android:value="@string/nativescript_google_maps_api_key"/>
        <activity android:name="com.telerik.pushplugin.PushHandlerActivity"/>
        <receiver android:exported="true" android:name="com.google.android.gms.gcm.GcmReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <category android:name="com.pushApp.gcm"/>
            </intent-filter>
        </receiver>
        <service android:exported="false" android:name="com.telerik.pushplugin.PushPlugin">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
            </intent-filter>
        </service>
        <activity android:configChanges="keyboardHidden|orientation|screenSize" android:label="@string/title_activity_kimera" android:name="com.tns.NativeScriptActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:name="com.tns.ErrorReportActivity"/>
        <activity android:exported="false" android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"/>
        <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
    </application>
</manifest>
```

**Comment by AntonDobrev** [comment]
@ickata The issue appears to be thrown due to the missing API key for Google Maps usage - can you please check it is added as expected by the maps module?

**Comment by ickata** [comment]
What I do is following the plugins instructions:
https://github.com/dapriett/nativescript-google-maps-sdk#setup-android-api-key

Before adding the push plugin, it was working fine.

**Comment by AntonDobrev** [comment]
@ickata I am not able to replicate the issue using both plugins - works as expected. The push plugin should not interfere with the Google Maps SDK and features. 

Given the workflow you explained you may want to:

- remove and add the Android platform (```tns remove platform```....) again
- double-check whether there is a _values_ folder inside AppResources with the respective XML file inside as shown [here](https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/demo/app/App_Resources/Android/values/nativescript_google_maps_api.xml)

**Comment by ickata** [comment]
@AntonDobrev – thanks. Removing and adding android platform solved the issue.
